# Generated by Django 4.1 on 2022-09-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('placeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='api.places')),
                ('lenreview', models.IntegerField()),
                ('service', models.DecimalField(decimal_places=2, max_digits=3)),
                ('atmosphere', models.DecimalField(decimal_places=2, max_digits=3)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('visit', models.DecimalField(decimal_places=2, max_digits=3)),
                ('taste', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'score',
                'managed': True,
            },
        ),
    ]
