# Generated by Django 4.1 on 2022-09-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_score_placeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourapi',
            fields=[
                ('placeid', models.ForeignKey(db_column='placeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tourapi', serialize=False, to='api.places')),
                ('exist', models.IntegerField(default=0)),
                ('contentid', models.CharField(db_column='conetentID', max_length=12)),
                ('title', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('overview', models.TextField()),
                ('infocenter', models.CharField(max_length=300)),
                ('restdate', models.CharField(max_length=100)),
                ('usetime', models.CharField(max_length=300)),
                ('parking', models.CharField(max_length=10)),
                ('chkbabycarriage', models.CharField(max_length=10)),
                ('chkpet', models.CharField(max_length=10)),
                ('chkcreditcard', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tour',
                'managed': True,
            },
        ),
    ]
