# Generated by Django 4.1 on 2022-09-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tourapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourapi',
            name='contentid',
            field=models.CharField(db_column='contentID', max_length=12),
        ),
    ]
