# Generated by Django 4.1 on 2022-08-29 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('videoid', models.CharField(db_column='videoID', max_length=11, primary_key=True, serialize=False)),
                ('channelname', models.CharField(max_length=15)),
                ('region', models.CharField(blank=True, max_length=10, null=True)),
                ('region1', models.CharField(blank=True, max_length=10, null=True)),
                ('region2', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(blank=True, max_length=48, null=True)),
                ('youtime', models.DateField()),
                ('views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('idx', models.IntegerField()),
                ('placeid', models.CharField(db_column='placeID', max_length=12, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('paddress', models.CharField(max_length=50)),
                ('px', models.FloatField(db_column='pX')),
                ('py', models.FloatField(db_column='pY')),
                ('videoid', models.ForeignKey(db_column='videoID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='places', to='api.youtube')),
            ],
            options={
                'db_table': 'places',
                'managed': True,
            },
        ),
    ]
