# Generated by Django 4.1 on 2022-09-04 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='placeid',
            field=models.ForeignKey(db_column='placeID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='api.places'),
        ),
    ]
